package emailcheck

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"reflect"
	"strings"
	"sync/atomic"
	"testing"
)

// replay answers DoH requests from testdata/dns.json (recorded answers); unknown URLs get 599,
// which the checker must treat as a failed lookup.
type replay struct {
	answers map[string]json.RawMessage
	calls   atomic.Int32
}

func (r *replay) RoundTrip(req *http.Request) (*http.Response, error) {
	r.calls.Add(1)
	body, ok := r.answers[req.URL.String()]
	if !ok {
		return &http.Response{StatusCode: 599, Body: io.NopCloser(strings.NewReader("")), Request: req}, nil
	}
	return &http.Response{StatusCode: 200, Body: io.NopCloser(strings.NewReader(string(body))), Request: req}, nil
}

func newReplay(t *testing.T) *replay {
	t.Helper()
	b, err := os.ReadFile("testdata/dns.json")
	if err != nil {
		t.Fatal(err)
	}
	r := &replay{}
	if err := json.Unmarshal(b, &r.answers); err != nil {
		t.Fatal(err)
	}
	return r
}

func optionsFor(r *replay) Options {
	client := &http.Client{Transport: r}
	return Options{Lookup: func(ctx context.Context, d string) DomainInfo { return LookupDomain(ctx, d, client) }}
}

// The golden file holds the JavaScript engine's results for the same inputs and DNS answers
// (generated by the BounceLens build). Go must match it field for field.
func TestMatchesJavaScriptEngine(t *testing.T) {
	b, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var golden []struct {
		Inputs  []string `json:"inputs"`
		Results []Result `json:"results"`
		Summary Summary  `json:"summary"`
	}
	if err := json.Unmarshal(b, &golden); err != nil {
		t.Fatal(err)
	}
	for _, g := range golden {
		got := CheckWith(context.Background(), g.Inputs, optionsFor(newReplay(t)))
		for i := range g.Inputs {
			if !reflect.DeepEqual(got[i], g.Results[i]) {
				gj, _ := json.Marshal(got[i])
				wj, _ := json.Marshal(g.Results[i])
				t.Errorf("%q\n got: %s\nwant: %s", g.Inputs[i], gj, wj)
			}
		}
		if s := Summarize(got); s != g.Summary {
			t.Errorf("summary got %+v want %+v", s, g.Summary)
		}
	}
}

func TestEachDomainLookedUpOnce(t *testing.T) {
	r := newReplay(t)
	CheckWith(context.Background(), []string{"a@gmail.com", "b@gmail.com", "c@Gmail.com"}, optionsFor(r))
	if n := r.calls.Load(); n != 1 {
		t.Fatalf("got %d DoH calls, want 1 (gmail.com MX)", n)
	}
}

func TestParse(t *testing.T) {
	if got := Parse("test@münchen.de").Domain; got != "xn--mnchen-3ya.de" {
		t.Errorf("IDN: got %q", got)
	}
	if got := Parse("mailto:John@Gmail.com").Email; got != "john@gmail.com" {
		t.Errorf("mailto: got %q", got)
	}
	if SuggestDomain("gmx.com") != "" {
		t.Error("gmx.com is a real provider, not a typo of gmail.com")
	}
	if SuggestDomain("gmial.com") != "gmail.com" {
		t.Error("gmial.com should suggest gmail.com")
	}
}

func TestDisposableList(t *testing.T) {
	d := DisposableDomains()
	if len(d) < 1000 || !d["mailinator.com"] {
		t.Fatalf("disposable list looks wrong: %d domains", len(d))
	}
}

func TestStatusesWithResultJSON(t *testing.T) {
	r := CheckWith(context.Background(), []string{"bad@"}, optionsFor(newReplay(t)))[0]
	b, _ := json.Marshal(r)
	want := `{"input":"bad@","email":null,"status":"invalid","reasons":["Missing @ or missing part"],` +
		`"flags":{"disposable":false,"role":false,"free":false,"duplicate":false,"gateway":false},` +
		`"did_you_mean":null,"provider":null,"mx":null}`
	if string(b) != want {
		t.Errorf("JSON shape changed:\n got %s\nwant %s", b, want)
	}
}
